name: Build and Publish Docker Image

on:
  release:
    types: [created]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app/
          file: ./app/Dockerfile.server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/plandex-server:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/plandex-server:latest