name: Build and publish Docker Image if a new Github release was created

on:
  release:
    types: [created]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      SANITIZED_REF_NAME: ${{ github.ref_name && replace(github.ref_name, '/', '-') }}

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./app/
          file: ./app/Dockerfile.server
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/plandex-server:${{ env.SANITIZED_REF_NAME }}
            ghcr.io/${{ github.repository_owner }}/plandex-server:latest
